racemanager/racemanager/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from homepage.views import HomePageView

admin.site.header = 'NCCX administration'

urlpatterns = patterns('',
    url(
        r'^$',
        HomePageView.as_view(),
        name='home'
    ),
    url(
        r'^races/',
        include('races.urls', namespace='races'),
    ),
    url(
        r'^administration/',
        include(admin.site.urls)
    ),
    url(
        r'^administration/doc/',
        include('django.contrib.admindocs.urls')
    ),
    # url(
    #     r'^pages/',
    #     include('django.contrib.flatpages.urls')
    # ),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += patterns('django.contrib.flatpages.views',
#     (r'^(?P<url>.*/)$', 'flatpage'),
# )

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
                            url(r'^__debug__/', include(debug_toolbar.urls)),
                            )

racemanager/races/urls.py
from django.conf.urls import patterns, include, url

from races.views import RaceDetailView, CurrentSeasonRaceListView, SeasonListView, CurrentSeasonRaceResultsListView


urlpatterns = patterns('',
    url(
        r'^$',
        SeasonListView.as_view(),
        name='season_list'
    ),
    url(
        r'^(?P<slug>[\w-]+)/$',
        CurrentSeasonRaceListView.as_view(),
        name='current_season_race_list'
    ),
    url(
        r'^(?P<slug>[\w-]+)/past-races-and-results/$',
        CurrentSeasonRaceResultsListView.as_view(),
        name='current_season_past_race_list'
    ),
    url(
        r'^(?P<slug>[\w-]+)/(?P<pk>\d+)/$',
        RaceDetailView.as_view(),
        name='race_detail'
    ),
)

racemanager/templates/base_generic.html
<!DOCTYPE html>
{% load static %}
{% load current_season %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}</title>

    {% block css %}{% endblock css %}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <header>
        <h1 class="branding">North Carolina Cyclo-cross</h1>
        <h2 class="current_season">{% current_season %} Season</h2>
        <nav role="primary">
            <ul>
                <li><a href="{% url 'races:current_season_race_list' season.slug  %}">Races</a></li>
                <li><a href="{% url 'races:current_season_past_race_list' season.slug  %}">Results</a></li>
                <li><a href="">About</a></li>
                <li><a href="">Contact</a></li>
            </ul>
        </nav>
        <div class="hero_image">
            <!-- Need to add thumbnailer for hero images -->
            <!-- <img src="http://placehold.it/1700x750" alt="NCCX"> -->
        </div>
    </header>
    <div class="container">
    {% block race_nav %}{% endblock %}
    {% block content %}{% endblock content %}
    </div>
    {% block js %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    {% endblock js %}
    <div class="container">
        <footer>
            <p>The NC Cyclo-cross Series is promoted/organized by the NCCX, a USA Cycling official racing club.</p>
            <p><a href="tel:8286749782">(828)674-9782</a> &amp; <a href="mailto:timothyhopkin@yahoo.com">timothyhopkin@yahoo.com</a></p>
        </footer>
    </div>
</body>
</html>

racemanager/templates/base_race.html
{% extends 'base_generic.html' %}
{% load current_season %}

{% block race_nav %}
<nav role="race">
    <ul>
        <li><a href="">Upcoming {{ current_season }} races</a></li>
        <li><a href="">past races &amp; results</a></li>
    </ul>
</nav>
{% endblock %}

racemanager/templates/home.html
{% extends 'base_generic.html' %}

{% block title %}North Carolina Cyclo-cross Series{% endblock title %}

{% block content %}
<section class="upcoming_races">
    <div class="season_results">
        <h2>Results</h2>
    {% if current_season.has_results %}
        <p>
        {% if current_season.get_results|length_is:'2' %}
        <a href="{{ current_season.get_results.0 }}">View</a> or <a href="{{ current_season.get_results.1 }}">download</a> results
        {% else %}
        <a href="{{ current_season.get_results }}">View results</a>
        {% endif %}
        for all past races in the {{ current_season }} season.
        </p>
    {% else %}
        <p>Results for the {{ current_season }} season are being tabulated. Check back soon!</p>
    {% endif %}
    </div>
    {% if season.current_season_has_ended %}
    <p>The cyclo-cross season for {{ season }} has ended.</p>
    {% else %}
    <div class="races_this_weekend">
        <h2>This weekend</h2>
        {% if weekend_race_list %}
        <ul class="race_list">
        {% for race in weekend_race_list %}
            <li class="race">
                <h3 class="race_title"><a href="{{ race.get_absolute_url }}">{{ race.date }}: {{ race.location.city }}</a></h3>
                <p class="race_address">{{ race.location.address }} (<a href="https://maps.google.com?saddr=Current+Location&daddr={{ race.location.latitude }}, {{ race.location.longitude }}">directions</a>)</p>
                {% if race.pre_registration_link %}
                <a class="race_action" href="{{ race.pre_registration_link}}">Register</a>
                {% endif %}
                <p class="race_description">{{ race.description }}</p>
                <p class="race_organizer"><b>Race organizer:</b> {{ race.organizer.name }}, <a href="mailto:{{ race.organizer.email }}">{{ race.organizer.email }}</a>{% if race.organizer.phone %}, {{ race.organizer.phone }}{% endif %}</p>
            </li>
        {% endfor %}
        </ul>
        {% else %}
        <p>There are no races schedule for this weekend! Please check the schedule for other upcoming races.</p>
        {% endif %}
    </div>

    <div class="races_this_month">
        <h2>More races this month</h2>
        {% if remaining_races_for_month_list %}
        <ul class="race_list">
        {% for race in remaining_races_for_month_list %}
            <li class="race">
                <h3 class="race_title"><a href="{{ race.get_absolute_url }}">{{ race.date }}: {{ race.location.city }}</a></h3>
                <p class="race_address">{{ race.location.address }} (<a href="https://maps.google.com?saddr=Current+Location&daddr={{ race.location.latitude }}, {{ race.location.longitude }}">directions</a>)</p>
                {% if race.pre_registration_link %}
                <a class="race_action" href="{{ race.pre_registration_link}}">Register</a>
                {% endif %}
            </li>
        {% endfor %}
        </ul>
        {% else %}
        <ul class="race_list">
            {% for race in upcoming_races_for_next_month_list %}
            <li class="race">
                <h3 class="race_title"><a href="{{ race.get_absolute_url }}">{{ race.date }}: {{ race.location.city }}</a></h3>
                <p class="race_address">{{ race.location.address }} (<a href="https://maps.google.com?saddr=Current+Location&daddr={{ race.location.latitude }}, {{ race.location.longitude }}">directions</a>)</p>
                {% if race.pre_registration_link %}
                <a class="race_action" href="{{ race.pre_registration_link}}">Register</a>
                {% endif %}
            </li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    <p class="full_race_list">See <a href="{% url 'races:current_season_race_list' season.slug  %}">all races</a> for the {{ current_season }} season.</p>
    {% endif %}
</section>
{% endblock content %}